export const ORPC_ERROR_KINDS = {
  FILE_TOO_LARGE: "FILE_TOO_LARGE",
  INVALID_FILE_FORMAT: "INVALID_FILE_FORMAT",
  NETWORK: "NETWORK",
  PROVIDER_QUOTA: "PROVIDER_QUOTA",
  TIMEOUT: "TIMEOUT",
  UNEXPECTED: "UNEXPECTED",
  VALIDATION: "VALIDATION",
} as const;

export type ORPCErrorKind =
  (typeof ORPC_ERROR_KINDS)[keyof typeof ORPC_ERROR_KINDS];

export const ORPC_ERROR_MESSAGE_KEYS = {
  AI_UNAVAILABLE: "ORPC_ERROR_AI_UNAVAILABLE",
  FILE_TOO_LARGE: "ORPC_ERROR_FILE_TOO_LARGE",
  GENERIC: "ORPC_ERROR_GENERIC",
  INVALID_FILE_FORMAT: "ORPC_ERROR_INVALID_FILE_FORMAT",
  NETWORK: "ORPC_ERROR_NETWORK",
  TIMEOUT: "ORPC_ERROR_TIMEOUT",
  VALIDATION: "ORPC_ERROR_VALIDATION",
} as const;

export type ORPCErrorMessageKey =
  (typeof ORPC_ERROR_MESSAGE_KEYS)[keyof typeof ORPC_ERROR_MESSAGE_KEYS];

export const ORPC_ERROR_MESSAGE_KEY_BY_KIND: Record<
  ORPCErrorKind,
  ORPCErrorMessageKey
> = {
  FILE_TOO_LARGE: ORPC_ERROR_MESSAGE_KEYS.FILE_TOO_LARGE,
  INVALID_FILE_FORMAT: ORPC_ERROR_MESSAGE_KEYS.INVALID_FILE_FORMAT,
  NETWORK: ORPC_ERROR_MESSAGE_KEYS.NETWORK,
  PROVIDER_QUOTA: ORPC_ERROR_MESSAGE_KEYS.AI_UNAVAILABLE,
  TIMEOUT: ORPC_ERROR_MESSAGE_KEYS.TIMEOUT,
  UNEXPECTED: ORPC_ERROR_MESSAGE_KEYS.GENERIC,
  VALIDATION: ORPC_ERROR_MESSAGE_KEYS.VALIDATION,
};

export type ORPCSafeErrorData = {
  kind: ORPCErrorKind;
  procedure: string;
};
