/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as CvReviewRouteImport } from './routes/cv-review'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as dashboardLayoutRouteImport } from './routes/(dashboard)/layout'
import { Route as authLayoutRouteImport } from './routes/(auth)/layout'
import { Route as IndexRouteImport } from './routes/index'
import { Route as JobsIndexRouteImport } from './routes/jobs/index'
import { Route as JobsSlugRouteImport } from './routes/jobs/$slug'
import { Route as ApplyJobSlugRouteImport } from './routes/apply/$jobSlug'
import { Route as authSignUpRouteImport } from './routes/(auth)/sign-up'
import { Route as authSignInRouteImport } from './routes/(auth)/sign-in'
import { Route as authResetPasswordRouteImport } from './routes/(auth)/reset-password'
import { Route as authMagicLinkRouteImport } from './routes/(auth)/magic-link'
import { Route as authForgotPasswordRouteImport } from './routes/(auth)/forgot-password'
import { Route as dashboardSettingsLayoutRouteImport } from './routes/(dashboard)/settings/layout'
import { Route as ApiChatIndexRouteImport } from './routes/api/chat/index'
import { Route as dashboardSettingsIndexRouteImport } from './routes/(dashboard)/settings/index'
import { Route as dashboardOverviewIndexRouteImport } from './routes/(dashboard)/overview/index'
import { Route as dashboardOrganizationsIndexRouteImport } from './routes/(dashboard)/organizations/index'
import { Route as dashboardLabIndexRouteImport } from './routes/(dashboard)/lab/index'
import { Route as authTwoFactorIndexRouteImport } from './routes/(auth)/two-factor/index'
import { Route as ApiStorageSplatRouteImport } from './routes/api/storage/$'
import { Route as ApiRpcSplatRouteImport } from './routes/api/rpc.$'
import { Route as ApiChatResumeRouteImport } from './routes/api/chat/resume'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiAiJobDescriptionRouteImport } from './routes/api/ai/job-description'
import { Route as ApiAiJobChatRouteImport } from './routes/api/ai/job-chat'
import { Route as ApiAiCvReviewRouteImport } from './routes/api/ai/cv-review'
import { Route as dashboardSettingsSecurityRouteImport } from './routes/(dashboard)/settings/security'
import { Route as dashboardSettingsBillingRouteImport } from './routes/(dashboard)/settings/billing'
import { Route as dashboardSettingsAppearanceRouteImport } from './routes/(dashboard)/settings/appearance'
import { Route as authTwoFactorOtpRouteImport } from './routes/(auth)/two-factor/otp'
import { Route as authAcceptInvitationInvitationIdRouteImport } from './routes/(auth)/accept-invitation/$invitationId'
import { Route as ApiLabBlockGeneratorIndexRouteImport } from './routes/api/lab/block-generator/index'
import { Route as dashboardOrganizationsInvitationsIndexRouteImport } from './routes/(dashboard)/organizations/invitations/index'
import { Route as dashboardLabJobEditorIndexRouteImport } from './routes/(dashboard)/lab/job-editor/index'
import { Route as dashboardLabChatIndexRouteImport } from './routes/(dashboard)/lab/chat/index'
import { Route as dashboardLabBlockGeneratorIndexRouteImport } from './routes/(dashboard)/lab/block-generator/index'
import { Route as dashboardAdminJobsIndexRouteImport } from './routes/(dashboard)/admin/jobs/index'
import { Route as dashboardAdminApplicationsIndexRouteImport } from './routes/(dashboard)/admin/applications/index'
import { Route as dashboardAdminJobsJobIdRouteImport } from './routes/(dashboard)/admin/jobs/$jobId'
import { Route as dashboardAdminApplicationsIdRouteImport } from './routes/(dashboard)/admin/applications/$id'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const CvReviewRoute = CvReviewRouteImport.update({
  id: '/cv-review',
  path: '/cv-review',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const dashboardLayoutRoute = dashboardLayoutRouteImport.update({
  id: '/(dashboard)',
  getParentRoute: () => rootRouteImport,
} as any)
const authLayoutRoute = authLayoutRouteImport.update({
  id: '/(auth)',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsIndexRoute = JobsIndexRouteImport.update({
  id: '/jobs/',
  path: '/jobs/',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsSlugRoute = JobsSlugRouteImport.update({
  id: '/jobs/$slug',
  path: '/jobs/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplyJobSlugRoute = ApplyJobSlugRouteImport.update({
  id: '/apply/$jobSlug',
  path: '/apply/$jobSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignUpRoute = authSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => authLayoutRoute,
} as any)
const authSignInRoute = authSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => authLayoutRoute,
} as any)
const authResetPasswordRoute = authResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => authLayoutRoute,
} as any)
const authMagicLinkRoute = authMagicLinkRouteImport.update({
  id: '/magic-link',
  path: '/magic-link',
  getParentRoute: () => authLayoutRoute,
} as any)
const authForgotPasswordRoute = authForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => authLayoutRoute,
} as any)
const dashboardSettingsLayoutRoute = dashboardSettingsLayoutRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => dashboardLayoutRoute,
} as any)
const ApiChatIndexRoute = ApiChatIndexRouteImport.update({
  id: '/api/chat/',
  path: '/api/chat/',
  getParentRoute: () => rootRouteImport,
} as any)
const dashboardSettingsIndexRoute = dashboardSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => dashboardSettingsLayoutRoute,
} as any)
const dashboardOverviewIndexRoute = dashboardOverviewIndexRouteImport.update({
  id: '/overview/',
  path: '/overview/',
  getParentRoute: () => dashboardLayoutRoute,
} as any)
const dashboardOrganizationsIndexRoute =
  dashboardOrganizationsIndexRouteImport.update({
    id: '/organizations/',
    path: '/organizations/',
    getParentRoute: () => dashboardLayoutRoute,
  } as any)
const dashboardLabIndexRoute = dashboardLabIndexRouteImport.update({
  id: '/lab/',
  path: '/lab/',
  getParentRoute: () => dashboardLayoutRoute,
} as any)
const authTwoFactorIndexRoute = authTwoFactorIndexRouteImport.update({
  id: '/two-factor/',
  path: '/two-factor/',
  getParentRoute: () => authLayoutRoute,
} as any)
const ApiStorageSplatRoute = ApiStorageSplatRouteImport.update({
  id: '/api/storage/$',
  path: '/api/storage/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRpcSplatRoute = ApiRpcSplatRouteImport.update({
  id: '/api/rpc/$',
  path: '/api/rpc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatResumeRoute = ApiChatResumeRouteImport.update({
  id: '/api/chat/resume',
  path: '/api/chat/resume',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiJobDescriptionRoute = ApiAiJobDescriptionRouteImport.update({
  id: '/api/ai/job-description',
  path: '/api/ai/job-description',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiJobChatRoute = ApiAiJobChatRouteImport.update({
  id: '/api/ai/job-chat',
  path: '/api/ai/job-chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiCvReviewRoute = ApiAiCvReviewRouteImport.update({
  id: '/api/ai/cv-review',
  path: '/api/ai/cv-review',
  getParentRoute: () => rootRouteImport,
} as any)
const dashboardSettingsSecurityRoute =
  dashboardSettingsSecurityRouteImport.update({
    id: '/security',
    path: '/security',
    getParentRoute: () => dashboardSettingsLayoutRoute,
  } as any)
const dashboardSettingsBillingRoute =
  dashboardSettingsBillingRouteImport.update({
    id: '/billing',
    path: '/billing',
    getParentRoute: () => dashboardSettingsLayoutRoute,
  } as any)
const dashboardSettingsAppearanceRoute =
  dashboardSettingsAppearanceRouteImport.update({
    id: '/appearance',
    path: '/appearance',
    getParentRoute: () => dashboardSettingsLayoutRoute,
  } as any)
const authTwoFactorOtpRoute = authTwoFactorOtpRouteImport.update({
  id: '/two-factor/otp',
  path: '/two-factor/otp',
  getParentRoute: () => authLayoutRoute,
} as any)
const authAcceptInvitationInvitationIdRoute =
  authAcceptInvitationInvitationIdRouteImport.update({
    id: '/accept-invitation/$invitationId',
    path: '/accept-invitation/$invitationId',
    getParentRoute: () => authLayoutRoute,
  } as any)
const ApiLabBlockGeneratorIndexRoute =
  ApiLabBlockGeneratorIndexRouteImport.update({
    id: '/api/lab/block-generator/',
    path: '/api/lab/block-generator/',
    getParentRoute: () => rootRouteImport,
  } as any)
const dashboardOrganizationsInvitationsIndexRoute =
  dashboardOrganizationsInvitationsIndexRouteImport.update({
    id: '/organizations/invitations/',
    path: '/organizations/invitations/',
    getParentRoute: () => dashboardLayoutRoute,
  } as any)
const dashboardLabJobEditorIndexRoute =
  dashboardLabJobEditorIndexRouteImport.update({
    id: '/lab/job-editor/',
    path: '/lab/job-editor/',
    getParentRoute: () => dashboardLayoutRoute,
  } as any)
const dashboardLabChatIndexRoute = dashboardLabChatIndexRouteImport.update({
  id: '/lab/chat/',
  path: '/lab/chat/',
  getParentRoute: () => dashboardLayoutRoute,
} as any)
const dashboardLabBlockGeneratorIndexRoute =
  dashboardLabBlockGeneratorIndexRouteImport.update({
    id: '/lab/block-generator/',
    path: '/lab/block-generator/',
    getParentRoute: () => dashboardLayoutRoute,
  } as any)
const dashboardAdminJobsIndexRoute = dashboardAdminJobsIndexRouteImport.update({
  id: '/admin/jobs/',
  path: '/admin/jobs/',
  getParentRoute: () => dashboardLayoutRoute,
} as any)
const dashboardAdminApplicationsIndexRoute =
  dashboardAdminApplicationsIndexRouteImport.update({
    id: '/admin/applications/',
    path: '/admin/applications/',
    getParentRoute: () => dashboardLayoutRoute,
  } as any)
const dashboardAdminJobsJobIdRoute = dashboardAdminJobsJobIdRouteImport.update({
  id: '/admin/jobs/$jobId',
  path: '/admin/jobs/$jobId',
  getParentRoute: () => dashboardLayoutRoute,
} as any)
const dashboardAdminApplicationsIdRoute =
  dashboardAdminApplicationsIdRouteImport.update({
    id: '/admin/applications/$id',
    path: '/admin/applications/$id',
    getParentRoute: () => dashboardLayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/cv-review': typeof CvReviewRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/settings': typeof dashboardSettingsLayoutRouteWithChildren
  '/forgot-password': typeof authForgotPasswordRoute
  '/magic-link': typeof authMagicLinkRoute
  '/reset-password': typeof authResetPasswordRoute
  '/sign-in': typeof authSignInRoute
  '/sign-up': typeof authSignUpRoute
  '/apply/$jobSlug': typeof ApplyJobSlugRoute
  '/jobs/$slug': typeof JobsSlugRoute
  '/jobs/': typeof JobsIndexRoute
  '/accept-invitation/$invitationId': typeof authAcceptInvitationInvitationIdRoute
  '/two-factor/otp': typeof authTwoFactorOtpRoute
  '/settings/appearance': typeof dashboardSettingsAppearanceRoute
  '/settings/billing': typeof dashboardSettingsBillingRoute
  '/settings/security': typeof dashboardSettingsSecurityRoute
  '/api/ai/cv-review': typeof ApiAiCvReviewRoute
  '/api/ai/job-chat': typeof ApiAiJobChatRoute
  '/api/ai/job-description': typeof ApiAiJobDescriptionRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/chat/resume': typeof ApiChatResumeRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/api/storage/$': typeof ApiStorageSplatRoute
  '/two-factor/': typeof authTwoFactorIndexRoute
  '/lab/': typeof dashboardLabIndexRoute
  '/organizations/': typeof dashboardOrganizationsIndexRoute
  '/overview/': typeof dashboardOverviewIndexRoute
  '/settings/': typeof dashboardSettingsIndexRoute
  '/api/chat/': typeof ApiChatIndexRoute
  '/admin/applications/$id': typeof dashboardAdminApplicationsIdRoute
  '/admin/jobs/$jobId': typeof dashboardAdminJobsJobIdRoute
  '/admin/applications/': typeof dashboardAdminApplicationsIndexRoute
  '/admin/jobs/': typeof dashboardAdminJobsIndexRoute
  '/lab/block-generator/': typeof dashboardLabBlockGeneratorIndexRoute
  '/lab/chat/': typeof dashboardLabChatIndexRoute
  '/lab/job-editor/': typeof dashboardLabJobEditorIndexRoute
  '/organizations/invitations/': typeof dashboardOrganizationsInvitationsIndexRoute
  '/api/lab/block-generator/': typeof ApiLabBlockGeneratorIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/cv-review': typeof CvReviewRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/forgot-password': typeof authForgotPasswordRoute
  '/magic-link': typeof authMagicLinkRoute
  '/reset-password': typeof authResetPasswordRoute
  '/sign-in': typeof authSignInRoute
  '/sign-up': typeof authSignUpRoute
  '/apply/$jobSlug': typeof ApplyJobSlugRoute
  '/jobs/$slug': typeof JobsSlugRoute
  '/jobs': typeof JobsIndexRoute
  '/accept-invitation/$invitationId': typeof authAcceptInvitationInvitationIdRoute
  '/two-factor/otp': typeof authTwoFactorOtpRoute
  '/settings/appearance': typeof dashboardSettingsAppearanceRoute
  '/settings/billing': typeof dashboardSettingsBillingRoute
  '/settings/security': typeof dashboardSettingsSecurityRoute
  '/api/ai/cv-review': typeof ApiAiCvReviewRoute
  '/api/ai/job-chat': typeof ApiAiJobChatRoute
  '/api/ai/job-description': typeof ApiAiJobDescriptionRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/chat/resume': typeof ApiChatResumeRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/api/storage/$': typeof ApiStorageSplatRoute
  '/two-factor': typeof authTwoFactorIndexRoute
  '/lab': typeof dashboardLabIndexRoute
  '/organizations': typeof dashboardOrganizationsIndexRoute
  '/overview': typeof dashboardOverviewIndexRoute
  '/settings': typeof dashboardSettingsIndexRoute
  '/api/chat': typeof ApiChatIndexRoute
  '/admin/applications/$id': typeof dashboardAdminApplicationsIdRoute
  '/admin/jobs/$jobId': typeof dashboardAdminJobsJobIdRoute
  '/admin/applications': typeof dashboardAdminApplicationsIndexRoute
  '/admin/jobs': typeof dashboardAdminJobsIndexRoute
  '/lab/block-generator': typeof dashboardLabBlockGeneratorIndexRoute
  '/lab/chat': typeof dashboardLabChatIndexRoute
  '/lab/job-editor': typeof dashboardLabJobEditorIndexRoute
  '/organizations/invitations': typeof dashboardOrganizationsInvitationsIndexRoute
  '/api/lab/block-generator': typeof ApiLabBlockGeneratorIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(auth)': typeof authLayoutRouteWithChildren
  '/(dashboard)': typeof dashboardLayoutRouteWithChildren
  '/contact': typeof ContactRoute
  '/cv-review': typeof CvReviewRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/(dashboard)/settings': typeof dashboardSettingsLayoutRouteWithChildren
  '/(auth)/forgot-password': typeof authForgotPasswordRoute
  '/(auth)/magic-link': typeof authMagicLinkRoute
  '/(auth)/reset-password': typeof authResetPasswordRoute
  '/(auth)/sign-in': typeof authSignInRoute
  '/(auth)/sign-up': typeof authSignUpRoute
  '/apply/$jobSlug': typeof ApplyJobSlugRoute
  '/jobs/$slug': typeof JobsSlugRoute
  '/jobs/': typeof JobsIndexRoute
  '/(auth)/accept-invitation/$invitationId': typeof authAcceptInvitationInvitationIdRoute
  '/(auth)/two-factor/otp': typeof authTwoFactorOtpRoute
  '/(dashboard)/settings/appearance': typeof dashboardSettingsAppearanceRoute
  '/(dashboard)/settings/billing': typeof dashboardSettingsBillingRoute
  '/(dashboard)/settings/security': typeof dashboardSettingsSecurityRoute
  '/api/ai/cv-review': typeof ApiAiCvReviewRoute
  '/api/ai/job-chat': typeof ApiAiJobChatRoute
  '/api/ai/job-description': typeof ApiAiJobDescriptionRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/chat/resume': typeof ApiChatResumeRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/api/storage/$': typeof ApiStorageSplatRoute
  '/(auth)/two-factor/': typeof authTwoFactorIndexRoute
  '/(dashboard)/lab/': typeof dashboardLabIndexRoute
  '/(dashboard)/organizations/': typeof dashboardOrganizationsIndexRoute
  '/(dashboard)/overview/': typeof dashboardOverviewIndexRoute
  '/(dashboard)/settings/': typeof dashboardSettingsIndexRoute
  '/api/chat/': typeof ApiChatIndexRoute
  '/(dashboard)/admin/applications/$id': typeof dashboardAdminApplicationsIdRoute
  '/(dashboard)/admin/jobs/$jobId': typeof dashboardAdminJobsJobIdRoute
  '/(dashboard)/admin/applications/': typeof dashboardAdminApplicationsIndexRoute
  '/(dashboard)/admin/jobs/': typeof dashboardAdminJobsIndexRoute
  '/(dashboard)/lab/block-generator/': typeof dashboardLabBlockGeneratorIndexRoute
  '/(dashboard)/lab/chat/': typeof dashboardLabChatIndexRoute
  '/(dashboard)/lab/job-editor/': typeof dashboardLabJobEditorIndexRoute
  '/(dashboard)/organizations/invitations/': typeof dashboardOrganizationsInvitationsIndexRoute
  '/api/lab/block-generator/': typeof ApiLabBlockGeneratorIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contact'
    | '/cv-review'
    | '/pricing'
    | '/privacy'
    | '/terms'
    | '/settings'
    | '/forgot-password'
    | '/magic-link'
    | '/reset-password'
    | '/sign-in'
    | '/sign-up'
    | '/apply/$jobSlug'
    | '/jobs/$slug'
    | '/jobs/'
    | '/accept-invitation/$invitationId'
    | '/two-factor/otp'
    | '/settings/appearance'
    | '/settings/billing'
    | '/settings/security'
    | '/api/ai/cv-review'
    | '/api/ai/job-chat'
    | '/api/ai/job-description'
    | '/api/auth/$'
    | '/api/chat/resume'
    | '/api/rpc/$'
    | '/api/storage/$'
    | '/two-factor/'
    | '/lab/'
    | '/organizations/'
    | '/overview/'
    | '/settings/'
    | '/api/chat/'
    | '/admin/applications/$id'
    | '/admin/jobs/$jobId'
    | '/admin/applications/'
    | '/admin/jobs/'
    | '/lab/block-generator/'
    | '/lab/chat/'
    | '/lab/job-editor/'
    | '/organizations/invitations/'
    | '/api/lab/block-generator/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contact'
    | '/cv-review'
    | '/pricing'
    | '/privacy'
    | '/terms'
    | '/forgot-password'
    | '/magic-link'
    | '/reset-password'
    | '/sign-in'
    | '/sign-up'
    | '/apply/$jobSlug'
    | '/jobs/$slug'
    | '/jobs'
    | '/accept-invitation/$invitationId'
    | '/two-factor/otp'
    | '/settings/appearance'
    | '/settings/billing'
    | '/settings/security'
    | '/api/ai/cv-review'
    | '/api/ai/job-chat'
    | '/api/ai/job-description'
    | '/api/auth/$'
    | '/api/chat/resume'
    | '/api/rpc/$'
    | '/api/storage/$'
    | '/two-factor'
    | '/lab'
    | '/organizations'
    | '/overview'
    | '/settings'
    | '/api/chat'
    | '/admin/applications/$id'
    | '/admin/jobs/$jobId'
    | '/admin/applications'
    | '/admin/jobs'
    | '/lab/block-generator'
    | '/lab/chat'
    | '/lab/job-editor'
    | '/organizations/invitations'
    | '/api/lab/block-generator'
  id:
    | '__root__'
    | '/'
    | '/(auth)'
    | '/(dashboard)'
    | '/contact'
    | '/cv-review'
    | '/pricing'
    | '/privacy'
    | '/terms'
    | '/(dashboard)/settings'
    | '/(auth)/forgot-password'
    | '/(auth)/magic-link'
    | '/(auth)/reset-password'
    | '/(auth)/sign-in'
    | '/(auth)/sign-up'
    | '/apply/$jobSlug'
    | '/jobs/$slug'
    | '/jobs/'
    | '/(auth)/accept-invitation/$invitationId'
    | '/(auth)/two-factor/otp'
    | '/(dashboard)/settings/appearance'
    | '/(dashboard)/settings/billing'
    | '/(dashboard)/settings/security'
    | '/api/ai/cv-review'
    | '/api/ai/job-chat'
    | '/api/ai/job-description'
    | '/api/auth/$'
    | '/api/chat/resume'
    | '/api/rpc/$'
    | '/api/storage/$'
    | '/(auth)/two-factor/'
    | '/(dashboard)/lab/'
    | '/(dashboard)/organizations/'
    | '/(dashboard)/overview/'
    | '/(dashboard)/settings/'
    | '/api/chat/'
    | '/(dashboard)/admin/applications/$id'
    | '/(dashboard)/admin/jobs/$jobId'
    | '/(dashboard)/admin/applications/'
    | '/(dashboard)/admin/jobs/'
    | '/(dashboard)/lab/block-generator/'
    | '/(dashboard)/lab/chat/'
    | '/(dashboard)/lab/job-editor/'
    | '/(dashboard)/organizations/invitations/'
    | '/api/lab/block-generator/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  authLayoutRoute: typeof authLayoutRouteWithChildren
  dashboardLayoutRoute: typeof dashboardLayoutRouteWithChildren
  ContactRoute: typeof ContactRoute
  CvReviewRoute: typeof CvReviewRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
  ApplyJobSlugRoute: typeof ApplyJobSlugRoute
  JobsSlugRoute: typeof JobsSlugRoute
  JobsIndexRoute: typeof JobsIndexRoute
  ApiAiCvReviewRoute: typeof ApiAiCvReviewRoute
  ApiAiJobChatRoute: typeof ApiAiJobChatRoute
  ApiAiJobDescriptionRoute: typeof ApiAiJobDescriptionRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiChatResumeRoute: typeof ApiChatResumeRoute
  ApiRpcSplatRoute: typeof ApiRpcSplatRoute
  ApiStorageSplatRoute: typeof ApiStorageSplatRoute
  ApiChatIndexRoute: typeof ApiChatIndexRoute
  ApiLabBlockGeneratorIndexRoute: typeof ApiLabBlockGeneratorIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cv-review': {
      id: '/cv-review'
      path: '/cv-review'
      fullPath: '/cv-review'
      preLoaderRoute: typeof CvReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(dashboard)': {
      id: '/(dashboard)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof dashboardLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)': {
      id: '/(auth)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/': {
      id: '/jobs/'
      path: '/jobs'
      fullPath: '/jobs/'
      preLoaderRoute: typeof JobsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/$slug': {
      id: '/jobs/$slug'
      path: '/jobs/$slug'
      fullPath: '/jobs/$slug'
      preLoaderRoute: typeof JobsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apply/$jobSlug': {
      id: '/apply/$jobSlug'
      path: '/apply/$jobSlug'
      fullPath: '/apply/$jobSlug'
      preLoaderRoute: typeof ApplyJobSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-up': {
      id: '/(auth)/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof authSignUpRouteImport
      parentRoute: typeof authLayoutRoute
    }
    '/(auth)/sign-in': {
      id: '/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authSignInRouteImport
      parentRoute: typeof authLayoutRoute
    }
    '/(auth)/reset-password': {
      id: '/(auth)/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof authResetPasswordRouteImport
      parentRoute: typeof authLayoutRoute
    }
    '/(auth)/magic-link': {
      id: '/(auth)/magic-link'
      path: '/magic-link'
      fullPath: '/magic-link'
      preLoaderRoute: typeof authMagicLinkRouteImport
      parentRoute: typeof authLayoutRoute
    }
    '/(auth)/forgot-password': {
      id: '/(auth)/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof authForgotPasswordRouteImport
      parentRoute: typeof authLayoutRoute
    }
    '/(dashboard)/settings': {
      id: '/(dashboard)/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof dashboardSettingsLayoutRouteImport
      parentRoute: typeof dashboardLayoutRoute
    }
    '/api/chat/': {
      id: '/api/chat/'
      path: '/api/chat'
      fullPath: '/api/chat/'
      preLoaderRoute: typeof ApiChatIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(dashboard)/settings/': {
      id: '/(dashboard)/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof dashboardSettingsIndexRouteImport
      parentRoute: typeof dashboardSettingsLayoutRoute
    }
    '/(dashboard)/overview/': {
      id: '/(dashboard)/overview/'
      path: '/overview'
      fullPath: '/overview/'
      preLoaderRoute: typeof dashboardOverviewIndexRouteImport
      parentRoute: typeof dashboardLayoutRoute
    }
    '/(dashboard)/organizations/': {
      id: '/(dashboard)/organizations/'
      path: '/organizations'
      fullPath: '/organizations/'
      preLoaderRoute: typeof dashboardOrganizationsIndexRouteImport
      parentRoute: typeof dashboardLayoutRoute
    }
    '/(dashboard)/lab/': {
      id: '/(dashboard)/lab/'
      path: '/lab'
      fullPath: '/lab/'
      preLoaderRoute: typeof dashboardLabIndexRouteImport
      parentRoute: typeof dashboardLayoutRoute
    }
    '/(auth)/two-factor/': {
      id: '/(auth)/two-factor/'
      path: '/two-factor'
      fullPath: '/two-factor/'
      preLoaderRoute: typeof authTwoFactorIndexRouteImport
      parentRoute: typeof authLayoutRoute
    }
    '/api/storage/$': {
      id: '/api/storage/$'
      path: '/api/storage/$'
      fullPath: '/api/storage/$'
      preLoaderRoute: typeof ApiStorageSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/rpc/$': {
      id: '/api/rpc/$'
      path: '/api/rpc/$'
      fullPath: '/api/rpc/$'
      preLoaderRoute: typeof ApiRpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat/resume': {
      id: '/api/chat/resume'
      path: '/api/chat/resume'
      fullPath: '/api/chat/resume'
      preLoaderRoute: typeof ApiChatResumeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/job-description': {
      id: '/api/ai/job-description'
      path: '/api/ai/job-description'
      fullPath: '/api/ai/job-description'
      preLoaderRoute: typeof ApiAiJobDescriptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/job-chat': {
      id: '/api/ai/job-chat'
      path: '/api/ai/job-chat'
      fullPath: '/api/ai/job-chat'
      preLoaderRoute: typeof ApiAiJobChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/cv-review': {
      id: '/api/ai/cv-review'
      path: '/api/ai/cv-review'
      fullPath: '/api/ai/cv-review'
      preLoaderRoute: typeof ApiAiCvReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(dashboard)/settings/security': {
      id: '/(dashboard)/settings/security'
      path: '/security'
      fullPath: '/settings/security'
      preLoaderRoute: typeof dashboardSettingsSecurityRouteImport
      parentRoute: typeof dashboardSettingsLayoutRoute
    }
    '/(dashboard)/settings/billing': {
      id: '/(dashboard)/settings/billing'
      path: '/billing'
      fullPath: '/settings/billing'
      preLoaderRoute: typeof dashboardSettingsBillingRouteImport
      parentRoute: typeof dashboardSettingsLayoutRoute
    }
    '/(dashboard)/settings/appearance': {
      id: '/(dashboard)/settings/appearance'
      path: '/appearance'
      fullPath: '/settings/appearance'
      preLoaderRoute: typeof dashboardSettingsAppearanceRouteImport
      parentRoute: typeof dashboardSettingsLayoutRoute
    }
    '/(auth)/two-factor/otp': {
      id: '/(auth)/two-factor/otp'
      path: '/two-factor/otp'
      fullPath: '/two-factor/otp'
      preLoaderRoute: typeof authTwoFactorOtpRouteImport
      parentRoute: typeof authLayoutRoute
    }
    '/(auth)/accept-invitation/$invitationId': {
      id: '/(auth)/accept-invitation/$invitationId'
      path: '/accept-invitation/$invitationId'
      fullPath: '/accept-invitation/$invitationId'
      preLoaderRoute: typeof authAcceptInvitationInvitationIdRouteImport
      parentRoute: typeof authLayoutRoute
    }
    '/api/lab/block-generator/': {
      id: '/api/lab/block-generator/'
      path: '/api/lab/block-generator'
      fullPath: '/api/lab/block-generator/'
      preLoaderRoute: typeof ApiLabBlockGeneratorIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(dashboard)/organizations/invitations/': {
      id: '/(dashboard)/organizations/invitations/'
      path: '/organizations/invitations'
      fullPath: '/organizations/invitations/'
      preLoaderRoute: typeof dashboardOrganizationsInvitationsIndexRouteImport
      parentRoute: typeof dashboardLayoutRoute
    }
    '/(dashboard)/lab/job-editor/': {
      id: '/(dashboard)/lab/job-editor/'
      path: '/lab/job-editor'
      fullPath: '/lab/job-editor/'
      preLoaderRoute: typeof dashboardLabJobEditorIndexRouteImport
      parentRoute: typeof dashboardLayoutRoute
    }
    '/(dashboard)/lab/chat/': {
      id: '/(dashboard)/lab/chat/'
      path: '/lab/chat'
      fullPath: '/lab/chat/'
      preLoaderRoute: typeof dashboardLabChatIndexRouteImport
      parentRoute: typeof dashboardLayoutRoute
    }
    '/(dashboard)/lab/block-generator/': {
      id: '/(dashboard)/lab/block-generator/'
      path: '/lab/block-generator'
      fullPath: '/lab/block-generator/'
      preLoaderRoute: typeof dashboardLabBlockGeneratorIndexRouteImport
      parentRoute: typeof dashboardLayoutRoute
    }
    '/(dashboard)/admin/jobs/': {
      id: '/(dashboard)/admin/jobs/'
      path: '/admin/jobs'
      fullPath: '/admin/jobs/'
      preLoaderRoute: typeof dashboardAdminJobsIndexRouteImport
      parentRoute: typeof dashboardLayoutRoute
    }
    '/(dashboard)/admin/applications/': {
      id: '/(dashboard)/admin/applications/'
      path: '/admin/applications'
      fullPath: '/admin/applications/'
      preLoaderRoute: typeof dashboardAdminApplicationsIndexRouteImport
      parentRoute: typeof dashboardLayoutRoute
    }
    '/(dashboard)/admin/jobs/$jobId': {
      id: '/(dashboard)/admin/jobs/$jobId'
      path: '/admin/jobs/$jobId'
      fullPath: '/admin/jobs/$jobId'
      preLoaderRoute: typeof dashboardAdminJobsJobIdRouteImport
      parentRoute: typeof dashboardLayoutRoute
    }
    '/(dashboard)/admin/applications/$id': {
      id: '/(dashboard)/admin/applications/$id'
      path: '/admin/applications/$id'
      fullPath: '/admin/applications/$id'
      preLoaderRoute: typeof dashboardAdminApplicationsIdRouteImport
      parentRoute: typeof dashboardLayoutRoute
    }
  }
}

interface authLayoutRouteChildren {
  authForgotPasswordRoute: typeof authForgotPasswordRoute
  authMagicLinkRoute: typeof authMagicLinkRoute
  authResetPasswordRoute: typeof authResetPasswordRoute
  authSignInRoute: typeof authSignInRoute
  authSignUpRoute: typeof authSignUpRoute
  authAcceptInvitationInvitationIdRoute: typeof authAcceptInvitationInvitationIdRoute
  authTwoFactorOtpRoute: typeof authTwoFactorOtpRoute
  authTwoFactorIndexRoute: typeof authTwoFactorIndexRoute
}

const authLayoutRouteChildren: authLayoutRouteChildren = {
  authForgotPasswordRoute: authForgotPasswordRoute,
  authMagicLinkRoute: authMagicLinkRoute,
  authResetPasswordRoute: authResetPasswordRoute,
  authSignInRoute: authSignInRoute,
  authSignUpRoute: authSignUpRoute,
  authAcceptInvitationInvitationIdRoute: authAcceptInvitationInvitationIdRoute,
  authTwoFactorOtpRoute: authTwoFactorOtpRoute,
  authTwoFactorIndexRoute: authTwoFactorIndexRoute,
}

const authLayoutRouteWithChildren = authLayoutRoute._addFileChildren(
  authLayoutRouteChildren,
)

interface dashboardSettingsLayoutRouteChildren {
  dashboardSettingsAppearanceRoute: typeof dashboardSettingsAppearanceRoute
  dashboardSettingsBillingRoute: typeof dashboardSettingsBillingRoute
  dashboardSettingsSecurityRoute: typeof dashboardSettingsSecurityRoute
  dashboardSettingsIndexRoute: typeof dashboardSettingsIndexRoute
}

const dashboardSettingsLayoutRouteChildren: dashboardSettingsLayoutRouteChildren =
  {
    dashboardSettingsAppearanceRoute: dashboardSettingsAppearanceRoute,
    dashboardSettingsBillingRoute: dashboardSettingsBillingRoute,
    dashboardSettingsSecurityRoute: dashboardSettingsSecurityRoute,
    dashboardSettingsIndexRoute: dashboardSettingsIndexRoute,
  }

const dashboardSettingsLayoutRouteWithChildren =
  dashboardSettingsLayoutRoute._addFileChildren(
    dashboardSettingsLayoutRouteChildren,
  )

interface dashboardLayoutRouteChildren {
  dashboardSettingsLayoutRoute: typeof dashboardSettingsLayoutRouteWithChildren
  dashboardLabIndexRoute: typeof dashboardLabIndexRoute
  dashboardOrganizationsIndexRoute: typeof dashboardOrganizationsIndexRoute
  dashboardOverviewIndexRoute: typeof dashboardOverviewIndexRoute
  dashboardAdminApplicationsIdRoute: typeof dashboardAdminApplicationsIdRoute
  dashboardAdminJobsJobIdRoute: typeof dashboardAdminJobsJobIdRoute
  dashboardAdminApplicationsIndexRoute: typeof dashboardAdminApplicationsIndexRoute
  dashboardAdminJobsIndexRoute: typeof dashboardAdminJobsIndexRoute
  dashboardLabBlockGeneratorIndexRoute: typeof dashboardLabBlockGeneratorIndexRoute
  dashboardLabChatIndexRoute: typeof dashboardLabChatIndexRoute
  dashboardLabJobEditorIndexRoute: typeof dashboardLabJobEditorIndexRoute
  dashboardOrganizationsInvitationsIndexRoute: typeof dashboardOrganizationsInvitationsIndexRoute
}

const dashboardLayoutRouteChildren: dashboardLayoutRouteChildren = {
  dashboardSettingsLayoutRoute: dashboardSettingsLayoutRouteWithChildren,
  dashboardLabIndexRoute: dashboardLabIndexRoute,
  dashboardOrganizationsIndexRoute: dashboardOrganizationsIndexRoute,
  dashboardOverviewIndexRoute: dashboardOverviewIndexRoute,
  dashboardAdminApplicationsIdRoute: dashboardAdminApplicationsIdRoute,
  dashboardAdminJobsJobIdRoute: dashboardAdminJobsJobIdRoute,
  dashboardAdminApplicationsIndexRoute: dashboardAdminApplicationsIndexRoute,
  dashboardAdminJobsIndexRoute: dashboardAdminJobsIndexRoute,
  dashboardLabBlockGeneratorIndexRoute: dashboardLabBlockGeneratorIndexRoute,
  dashboardLabChatIndexRoute: dashboardLabChatIndexRoute,
  dashboardLabJobEditorIndexRoute: dashboardLabJobEditorIndexRoute,
  dashboardOrganizationsInvitationsIndexRoute:
    dashboardOrganizationsInvitationsIndexRoute,
}

const dashboardLayoutRouteWithChildren = dashboardLayoutRoute._addFileChildren(
  dashboardLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  authLayoutRoute: authLayoutRouteWithChildren,
  dashboardLayoutRoute: dashboardLayoutRouteWithChildren,
  ContactRoute: ContactRoute,
  CvReviewRoute: CvReviewRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
  ApplyJobSlugRoute: ApplyJobSlugRoute,
  JobsSlugRoute: JobsSlugRoute,
  JobsIndexRoute: JobsIndexRoute,
  ApiAiCvReviewRoute: ApiAiCvReviewRoute,
  ApiAiJobChatRoute: ApiAiJobChatRoute,
  ApiAiJobDescriptionRoute: ApiAiJobDescriptionRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiChatResumeRoute: ApiChatResumeRoute,
  ApiRpcSplatRoute: ApiRpcSplatRoute,
  ApiStorageSplatRoute: ApiStorageSplatRoute,
  ApiChatIndexRoute: ApiChatIndexRoute,
  ApiLabBlockGeneratorIndexRoute: ApiLabBlockGeneratorIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
